name: Meme Factory      # Giving a name to your Workflow (this thing will show up in the GitHub's Action Tab)
on: 
    push:
        paths:
            - '/Python_Stuff/meme_maker.py'     
        branches:
                - 'main'           # Triggers the Worlflow everytime you push a code when this file changes

jobs:                   # You define a job (group of steps). There can be multiple Jobs
    meme-time:
        runs-on: ubuntu-latest                 # Runs the job on an Ubuntu Linux VM provided by GitHub
        steps:
            #Step1: Download the repo files
            - name: Download the Repo files
              uses: actions/checkout@v4        # Downloads your repo files into the VM 

              #Step2 : Setup Python
            - name: Setup Python
              uses: actions/setup-python@v4    # It will install Python in that VM 
              with:
                python-version: '3.10'         # This will install Python version 3.10
              
                #Step3 : Install Pillow (Python Library for Images)
            - name: Install Dependencies
              run: pip install Pillow          # a Python library for image manipulation

              #Step4: Generate a meme from the latest commit message
            - name: Generate Meme 
              run: python ./Python_Stuff/meme_maker.py "(git log -1 --pretty=%B)" # This will extract the commit message

              #Step5: Upload meme artifact
            - name: Upload Meme
              uses: actions/upload-artifact@v4
              with:
                name: Fresh-meme
                path: meme-output.png  

