name: Meme Factory
on:
  push:
    paths:
      - 'Python_Stuff/meme_maker.py'

concurrency:
  group: meme-only-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-meme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # 👈 Crucial for git diff to work

      - name: Debug changed files
        run: |
          echo "=== Changed files ==="
          git diff --name-only HEAD~1 HEAD || echo "First commit (no parent)"
          echo "====================="
          
      - name: Verify exclusive trigger
        run: |
          if [[ -f "Python_Stuff/meme_maker.py" ]]; then
            echo "✅ meme_maker.py exists and was changed!"
          else
            echo "❌ File missing! Check path:"
            ls Python_Stuff/
            exit 1
          fi


# name: Meme Factory      # Giving a name to your Workflow (this thing will show up in the GitHub's Action Tab)
# on: 
#     push:
#         paths:
#             - '/Python_Stuff/meme_maker.py'     
 
# jobs: 
#     make-meme:
#       runs-on: ubuntu-latest
#       steps:
#             #Step1: Download the repo files
#             - name: Download the Repo files
#               uses: actions/checkout@v4        # Downloads your repo files into the VM 
            
#             #Step2: Debug the files
#             - name: Debug files
#               run: |
#                 echo "Current directory: $pwd"
#                 ls -R Python_Stuff/

#               #Step3 : Setup Python
#             - name: Setup Python
#               uses: actions/setup-python@v4    # It will install Python in that VM 
#               with:
#                 python-version: '3.10'         # This will install Python version 3.10
              
#                 #Step4 : Install Pillow (Python Library for Images)
#             - name: Install Dependencies
#               run: pip install Pillow          # a Python library for image manipulation

#               #Step5: Generate a meme from the latest commit message
#             - name: Generate Meme 
#               run: python ./Python_Stuff/meme_maker.py "(git log -1 --pretty=%B)" # This will extract the commit message

#               #Step6: Upload meme artifact
#             - name: Upload Meme
#               uses: actions/upload-artifact@v4
#               with:
#                 name: Fresh-meme
#                 path: meme-output.png  

